services:
  laravel:
    build:
      context: ./
      args:
        user: php_host
    ports:
      - 80:80
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=nerd
      - MYSQL_PASSWORD=nerdpass
      - MYSQL_DATABASE=nerdbase
      - MYSQL_ROOT_PASSWORD=nerdpassword
    volumes:
    - db-data:/var/lib/mysql
    - "./Initial DB table creation.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./DB levels adding.sql:/docker-entrypoint-initdb.d/2.sql"


volumes:
  db-data:
